### ISSUE TITLE
Feature Request: Set user properties via Identity Provider

### ISSUE THREAD

**Issue by B00tLoad** [ether/ep_openid_connect#1]
I was thinking about a feature, where it would be possible to set user properties like is_admin, canCreate and readOnly in the IdP instead of/additional to the settings.json.

**Comment by rhansen** [comment]
I need more information: What claims can your IdP provide? What do their values look like? Which scopes provide those claims? Do you need per-pad access controls?

**Comment by B00tLoad** [comment]
Sorry for not getting back to this earlier. It has been quite the stressfull week.
I have set up claims for the parameter names as they would be specified in the config file. The Claim JSON Type is set to boolean for all of them.
I don't think I need per-pad access controls.
