### ISSUE TITLE
Failed authentication from IP 127.0.0.1

### ISSUE THREAD

**Issue by kieste** [ether/ep_openid_connect#10]
This is my configuration:
* etherpad 1.8.16 (behind nginx proxy doing the ssl termination)
* ep_openid_connect 2.0.8
* keycloak 15.0.1

I am periodocally (every 20s) getting a `Failed authentication from IP 127.0.0.1` info in my log.
This is because in the authenticate hook the `userinfo` object lacks a `sub` property in this case.

User authentication is working properly. But I would like to get rid of the log message and/or understand what the cause is.
A new entry is written to the sessionstorage every 20s because of that!?

**Comment by rhansen** [comment]
Are you using Docker? If so, I think this line is the culprit: https://github.com/ether/etherpad-lite/blob/1.8.16/Dockerfile#L98

We probably ought to add an endpoint to Etherpad core specifically for health checking (perhaps following [this I-D](https://www.ietf.org/archive/id/draft-inadarei-api-health-check-06.html)), and make sure that endpoint doesn't create session state or log anything.

**Comment by rhansen** [comment]
I opened ether/etherpad-lite#5324 assuming that the culprit is the Docker health checking. If that turns out to not be true, please comment and I'll reopen this bug.
