### ISSUE TITLE
Bug: Required setting missing from settings.json: ep_openid_connect.base_url

### ISSUE THREAD

**Issue by alzayatm** [ether/ep_openid_connect#4]
Hi,

I'm trying to integrate this plugin with my etherpad instance running on CentOS 7. I'm receiving the following error in the logs:
`Required setting missing from settings.json: ep_openid_connect.base_url`

I have the base_url key set in my settings.json as follows:
`"ep_openid_connect": {
    "issuer": "XXXXXXXXXXX",
    "client_id": "etherpad",
    "client_secret": "XXXXXXXXX",
    "base_url": "XXXXXXXXXX",
    "prohibited_usernames": ["admin", "guest"]
  },
`

**Comment by rhansen** [comment]
Weird. I don't see anything wrong in the your pasted `settings.json` or in the ep_openid_connect source code.

Are you sure you don't have a typo? Are you sure you added it to `settings.json` and not `settings.json.template`?

**Comment by rhansen** [comment]
Closing as stale.
