### ISSUE TITLE
Feature request: search in roles claim for role

### ISSUE THREAD

**Issue by GodMod** [ether/ep_openid_connect#44]
IDPs like Keycloak provide a "roles" claim, like this:
```
[...]
  "realm": "sso",
  "roles": [
    "user",
    "application_admin",
    "etherpad_admin"
  ],
  "sub": "12345678"
```
It would be great if we can define that when user has role "etherpad_admin", that the user flag "is_admin" is set.
Currently, only checking if specific claims are set is possible.

**Comment by rhansen** [comment]
Is it difficult to add custom claims in Keycloak? If it's easy to add custom claims, then I hesitate to add more code to this plugin.

**Comment by Marmelatze** [comment]
This can be solved by a keycloak client scope mapper with a custom script:
![Bildschirmfoto 2022-04-25 um 08 09 57](https://user-images.githubusercontent.com/199681/165030330-920f74be-6705-45bf-ad1c-42de9e094d69.png)

Script:

```
/**
 * Available variables: 
 * user - the current user
 * realm - the current realm
 * token - the current token
 * userSession - the current userSession
 * keycloakSession - the current keycloakSession
 */

var client = keycloakSession.getContext().getClient();

var role = realm.getRole("admin");

exports = user.hasRole(role);
```

**Comment by GodMod** [comment]
Perfect, thank you @Marmelatze
