### ISSUE TITLE
Logout possible?

### ISSUE THREAD

**Issue by florianp15** [ether/ep_openid_connect#9]
I'm using the plugin with a self-hosted GitLab instance as the auth provider. The login works perfectly but logging out in GitLab seems to have no effect in Etherpad. Is there a way to log out in Etherpad?

**Comment by rhansen** [comment]
Yes, you can visit `/ep_openid_connect/logout` and that will log you out. If you install [ep_readonly_guest](https://github.com/ether/ep_readonly_guest#readme) you'll get a logout button that will log you out. If you don't want to grant read-only access to strangers, you can use [ep_button_link](https://github.com/ether/ep_button_link#readme) to add a button that links to `../ep_openid_connect/logout`.
